-- AlterTable SiteSettings network fields + Kiosk uiPort/serverUrl
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "serverPublicUrl" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "defaultHealthPort" INTEGER NOT NULL DEFAULT 47821;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "defaultUiPort" INTEGER NOT NULL DEFAULT 47820;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "corsOrigins" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "probeIntervalMs" INTEGER NOT NULL DEFAULT 30000;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "probeTimeoutMs" INTEGER NOT NULL DEFAULT 2500;

ALTER TABLE "Kiosk" ADD COLUMN IF NOT EXISTS "uiPort" INTEGER NOT NULL DEFAULT 47820;
ALTER TABLE "Kiosk" ADD COLUMN IF NOT EXISTS "serverUrl" TEXT;
